### ISSUE TITLE
Issue on running "python modules/Calendar.py --noauth_local_webserver"

### ISSUE THREAD

**Issue by dansinclair25** [marclave/Jasper-Google-Calendar#1]
```
pi@raspberrypi ~/jasper/client $ python modules/Calendar.py --noauth_local_webserver
Traceback (most recent call last):
  File "modules/Calendar.py", line 7, in <module>
    from app_utils import getTimezone
ImportError: No module named app_utils
```

**Comment by dansinclair25** [comment]
I've tried changing the import to;

`from client.app_utils import getTimezone`

But still no luck. Any idea?

/Dan

**Comment by dansinclair25** [comment]
I worked it out. There were 3 problems.

1) The import line should read `from client.app_utils import getTimezone`
2) The Client ID in Google needs to be for a native application.
3) running; `python modules/Calendar.py --noauth_local_webserver` doesn't work. You need to kill Jasper, then restart it manually using `./jasper.py`. Once that has restarted and authenticated, restart your Pi so that Jasper starts as it normally would.

Please can you update the README to show these changes?

/Dan

**Comment by marclave** [comment]
@dansinclair25 about to update, thoughts on the README?

**Comment by dansinclair25** [comment]
@marclave The README is much better!! Just a couple more things...

The README says `cp Software-Projects/JasperCalendar/Calendar.py <path to ..client/jasper/modules>` 
but `Software-Projects` is NOT the name of the directory that the gist was cloned to. It should be `cp Jasper-Google-Calendar/Calendar.py <path to ..client/jasper.modules>`.

You should also change the README to something like the following after you have downloaded and copied the `Calendar.py` file over to the modules directory;
- Open Calendar.py and add Client ID and Client secret to appropriate variables
- Kill Jasper 
  `ps ax | grep jasper` will return all processes of jasper that are running.
  `sudo kill <pid>` where `<pid>` is the PID of each process from the previous command
- Restart Jasper from Terminal on the Pi (i.e. don't SSH in)
  `./jasper.py`
  This should then open a web browser asking you to accept the authentication request. Accept it.
- Once accepted, Jasper will start up as normal.
- Add the following to the `__init.py` file in the `~/jasper/client` directory
  `from modules import Calendar`
- Restart the Pi
  `sudo reboot`

**Comment by marclave** [comment]
@dansinclair25 Updated!
